---
# tasks file for apigee-time-sync
- name: Update yum os packages
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - ntp
    - ntpdate

- name: Update statsdir
  lineinfile:
    dest: '{{ ntp_conf }}'
    line: 'statsdir {{ stats_dir }}'
    insertafter: '^driftfile {{ drift_filename }}'
    backup: yes

- name: Create dirs
  file:
    path: '{{ item }}'
    state: directory
  with_items:
  - '{{ stats_dir }}'

- name: Update with preferred iburst if provided
  lineinfile:
    dest: '{{ ntp_conf }}'
    line: 'server {{ preferred_server_ip }} iburst prefer'
    insertbefore: '^server 0.*$'
    state: present
    backup: yes
  when: preferred_server_ip is defined

- name: Prepare to update locale
  file:
    path: /etc/localtime
    state: absent

- name: Update locale
  file:
    dest: /etc/localtime
    src: '{{ timezone }}'
    state: link

- name: Start ntp server
  service:
    name: ntpd
    state: restarted
